### ISSUE TITLE
Can't execTran on MemberId

### ISSUE THREAD

**Issue by quanhv94** [pepabo/gmopg#32]
https://github.com/pepabo/gmopg/blob/a1898154e17cfdd43d339afb289aab8474f68ad9/src/client/tranable.ts#L33

I find out that execTran api does not pass SiteId and SitePass to post method.
So execTran does not work when pass MemberId instead of CardNo.

Please confirm this.
Note: execTran using MemberId require SiteId and SitePass

**Comment by linyows** [comment]
Yes, it seems that passing SiteID and SitePass requires additional information such as MemberID and CardSeq. 

I don't think the specification to combine multiple use cases into one API is complicated and bad.

**Comment by linyows** [comment]
If there are any improvements on this client, i am waiting for your pull-request.
